### ISSUE TITLE
[BUG] Thread federation awareness in latest

### ISSUE THREAD

**Issue by e-five256** [aclist/kbin-kes#218] opened 2023-09-25 19:54 UTC
**Describe the bug**

Due to recent changes in kbin, the federation awareness mod shows all article entries as local.

As of https://codeberg.org/Kbin/kbin-core/pulls/1007 the "more" menu on article entries has a new item "more from domain" which pushes the [dropdown the mod gets the entry instance from by one](https://github.com/aclist/kbin-kes/blob/main/mods/kbin-federation-awareness.user.js#L133) on article entries specifically. Comments still function as the dropdown menu was not effected for them.

This is only affecting instances that have updated since the PR, so it is not happening on kbin.social yet, but fedia.io / kbin.run show it and I assume it will eventually happen once kbin.social is updated.

**To Reproduce**
1. Go to https://fedia.io/
2. Enable Threads -> federation awareness in KES
4. Observe a local style applied to all posts regardless of location

**Expected behavior**
Posts from federated and moderated instances to appear styled differently

**KES version:**
- Version number 2.2.2

**Comment by aclist** [comment] 2023-09-26 13:30
Thanks for the clear description. This seems like a straightforward fix, but I suggest we wait for these changes to be mainlined to kbin.social. As you noted, some instances run the bleeding-edge/nightly builds of kbin, whereas kbin.social tends to run the "stable" version of the code. For this reason, KES targets kbin.social first and foremost and is not in lock-step with the nightly version.

If we try to target both stable and testing builds, it would necessarily complete things (and there is no reliable way of determining which of any given feature would need to be in lock-step with some arbitrary instance), so it is best to wait for upstream changes to propagate to all instances. While this causes a side effect of some of instances running the bleeding-edge code to not function correctly, this is a feature, not a bug. kbin.social is usually the last to update, so a feature being released there is generally indicative of it being available on all global instances.

Can you bump this ticket again when this behavior starts occurring on kbin.social, after which time we can patch the federation awareness mod to include the desired behavior?

**Comment by e-five256** [comment] 2023-11-09 19:46
As requested, according to https://kbin.social/m/kbinMeta/t/612526 the `kbin.social` instance has updated and this should be the experience there now.

**Comment by Pamasich** [comment] 2023-11-10 13:47
Can confirm, I came here because federation awareness seems to have stopped working on kbin.social.

**Comment by aclist** [comment] 2023-11-11 03:26
Thanks for the reports. A larger feature release (3.0.0) is coming next week with other changes, but I decided to hotfix this right away with version 2.2.4, which is live now.

Resolved by  fa04646

**Closed** 2023-11-11 03:26 UTC
Labels: bug

**Comment by aclist** [comment] 2023-11-11 04:17
As a postscript, I forgot to mention that I changed the logic to not be dependent on positional order in the list and hopefully something more robust that can withstand changes in the future (i.e., if other items get added to the dropdown list)
