### ISSUE TITLE
[BUG] Collapsible comments: last reply in a nested thread is missing expando line

### ISSUE THREAD

**Issue by honkaiimpact3rd** [aclist/kbin-kes#78] opened 2023-07-13 11:39 UTC
**Describe the bug**
When you add a new reply to something, a thread line isn't made (but it is made in [the previous separate version of the userscript before KES](https://greasyfork.org/scripts/468923-kbin-improved-collapsible-comments)). But it does appear after refreshing the tab. 

**To Reproduce**
1. Go to any thread
2. Reply to an existing comment

**Expected behavior**
A thread line to made

**Screenshots**
New reply doesn't have a thread line
![Screenshot_20230713_132922](https://github.com/aclist/kbin-kes/assets/107812489/c356187d-ac43-4708-8315-9cedc2a191f1)
![Screenshot_20230713_133536](https://github.com/aclist/kbin-kes/assets/107812489/d71852a7-0bfc-4bf0-9c25-c5b83afda6db)

But while using the other, separate version of the userscript, the thread line is here
![Screenshot_20230713_133006](https://github.com/aclist/kbin-kes/assets/107812489/266b5a71-7119-49cd-a448-2ad8202faedc)
![Screenshot_20230713_133734](https://github.com/aclist/kbin-kes/assets/107812489/768ae546-ffa6-4cb3-8ee5-2e2663dbe00e)

**KES version:**
- Version number 1.1.4

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Vivaldi (Chromium)

**Comment by aclist** [comment] 2023-07-16 18:34
Upon further investigation, the issue is here: 

```
    if (toggle) {
        if (document.querySelector('.entry-comment.nested') || !document.querySelector('.comments')) {
            return;
        }
```

The first branch of this condition is TRUE when submitting a new reply, so it returns from the toggle function without reapplying. But it seems like this logic is necessarily needed to handle collapsing/etc.

**Comment by aclist** [comment] 2023-07-25 06:17
Resolved by https://github.com/aclist/kbin-kes/pull/144

**Closed by aclist** 2023-07-25 06:17 UTC
Labels: bug, mod
