### ISSUE TITLE
[BUG] Search icon missing

### ISSUE THREAD

**Issue by Mokinono** [aclist/kbin-kes#123] opened 2023-07-16 01:09 UTC
**Describe the bug**
While using KES and Kbin Subscription Panel - the Search Button in the top right corne bugs and changes to the "Subs" Icon.

**To Reproduce**

1. Go to Kbin.social
2. activate KES and Kbin Subscription Panel or Kbin Usability Pack
3. See the Icon Change after refresh of page

**Expected behavior**
Normaly ther should still be the search icon

**Screenshots**

![Screenshot 2023-07-16 030301](https://github.com/aclist/kbin-kes/assets/139662138/69bcd57f-1709-471f-b8a9-aade0234ff30)

**KES version:**
- 1.2.0

**Extension and version:**
- TamperMonkey 
- 4.19.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox
 - Version 115.0.2

**Comment by aclist** [comment] 2023-07-16 01:10
This was fixed in 1.3.0. Please update and it should be resolved.

**Comment by aclist** [comment] 2023-07-16 01:11
Duplicate of https://github.com/aclist/kbin-kes/issues/73

**Comment by aclist** [comment] 2023-07-16 01:19
I'm sorry, I gave you misinformation. I'm not sure there even is a public-facing 1.3.0 release. I am looking into this again, please stand by.

**Comment by Mokinono** [comment] 2023-07-16 01:23
Hey - sorry for the duplicate. I must have missed it. Thank you for looking in to it! Love what you are doing!

**Comment by aclist** [comment] 2023-07-16 02:30
No worries at all, was able to reproduce it again. Looks like it was partially fixed the first time, but it needed to target the elements better because it was a race between Subscriptions Panel and KES to change the navbar, leading the wrong one to be picked. This is fixed for good now in `1.2.1`, which introduces a more robust method of handling it that should never conflict.

**Closed** 2023-07-16 08:54 UTC
Labels: bug
