### ISSUE TITLE
[BUG] Kbin update overrides appearance of input elements

### ISSUE THREAD

**Issue by aaronliu0130** [aclist/kbin-kes#224] opened 2023-11-19 20:46 UTC
![image](https://github.com/aclist/kbin-kes/assets/11874211/a4bf71ed-f72f-4d8e-91a4-9d3ce372e20e)

**Is your feature request related to a problem? Please describe.**
The current settings dialog is a bit unclear on whether each checkbox is for the text above or for the text below

**Describe the solution you'd like**
1. Include the settings descriptions ("logo type") as headings instead
2. Make checkbox and label on the same line and apply the label element to the labels so the checkbox can be toggled when you click on the label. Do similar things for other input elements

**Describe alternatives you've considered**
Since most settings only have one description, put the description inside the "Settings" heading

**Comment by aclist** [comment] 2023-11-20 05:58
Thanks for the report. This appears to actually be a bug caused by the new Kbin update overriding the default style of checkbox and radio input elements page-wide, and was also causing them to have this non-standard appearance/color, which isn't something KES did intentionally.

I'll make a change that explicitly sets the appearance of these elements to respect the browser's default settings and restore them to being adjacent to each other like before. It might be a few days, as I'd like to bundle this with other updates.

**Comment by aaronliu0130** [comment] 2023-11-20 12:39
Hmm… are the texts already label elements? I think that may be the actual issue. Even in kbin settings I can click on a label to trigger the checkbox, but not in KES settings.

**Comment by aclist** [comment] 2023-11-20 13:01
It is fixed on the testing branch if you want to try. Yes, the labels are present and clickable in KES. Kbin was just disabling default browser behavior and creating fancy animated checkboxes for input elements.

**Comment by aclist** [comment] 2023-11-20 13:04
Restored appearance to KES' original expected behavior following kbin update

![1700485361](https://github.com/aclist/kbin-kes/assets/92275929/af731dda-201d-458c-b01f-719a9058039e)

Resolved per f77539c

**Closed by aclist** 2023-11-20 13:04 UTC
Labels: proposal

**Comment by aclist** [comment] 2023-12-08 11:30
This feature is live in version `3.1.0`.
