### ISSUE TITLE
[MOD] Change comment/thread font size

### ISSUE THREAD

**Issue by artillect** [aclist/kbin-kes#72] opened 2023-07-12 20:34 UTC
**Is this request to port an existing userscript or mod, or create a new one?**
Link to the source script if applicable.

**Describe the solution you'd like**
Add the ability to adjust font sizes for threads and comments independent of the page's font size.

**Additional context**
For some users, the font size for comments/threads is too small, and increasing the font size impacts how the page is laid out on mobile. This comment is where this idea is from: https://kbin.social/m/kbinMeta/t/183928/-/comment/741140

**Comment by aclist** [comment] 2023-07-12 20:39
One thing we should start looking to do is consolidating features so that we don't have 1,000s of mods that, e.g., hide one element. It seems like this would fit well into a mod that controls a variety of different onscreen elements, and you can granularly adjust the ones you want. Or turn it off altogether.

```
Author: you
Dynamically changes the font size of elements

Headers [dropdown]
Comments [dropdown]
Post description [dropdown]
Usernames [dropdown]
```

etc

**Comment by artillect** [comment] 2023-07-12 23:00
I was just thinking about that, I think it's a good idea. Speaking of organizing things, it might be nice to sort some of the stuff from the general page into more specific pages so the options are a little more spread out. I think adding a few extra pages could be good once we add some more mods, like "Navigation" for example

**Comment by aclist** [comment] 2023-07-13 10:12
Yes, although we can't do that too much after a certain point, as it is liable to be confusing going forward, once people get accustomed to certain mods being in a certain place

**Comment by aclist** [comment] 2023-07-21 01:41
Closing as duplicate of https://github.com/aclist/kbin-kes/pull/171

**Closed by aclist** 2023-07-21 01:41 UTC
Labels: mod
